import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	loader: {
		'.wasm': 'binary'
	},
	plugins: [
		{
			name: "inline-wasm-plugin",
			setup(build) {
				build.onResolve({ filter: /\.wasm$/ }, args => {
					// Resolve to the actual WASM file in node_modules
					const wasmPath = path.resolve('node_modules/sql.js/dist/sql-wasm.wasm');
					return { path: wasmPath, namespace: 'wasm-binary' };
				});

				build.onLoad({ filter: /\.wasm$/, namespace: 'wasm-binary' }, async (args) => {
					// Read WASM file and convert to base64
					const bytes = await fs.promises.readFile(args.path);
					const base64 = bytes.toString('base64');

					// Return as JS module that exports the Uint8Array
					const contents = `
						const base64Str = "${base64}";
						const binaryStr = atob(base64Str);
						const bytes = new Uint8Array(binaryStr.length);
						for (let i = 0; i < binaryStr.length; i++) {
							bytes[i] = binaryStr.charCodeAt(i);
						}
						export default bytes.buffer;
					`;

					return { contents, loader: 'js' };
				});
			}
		}
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
